name: Main

on: [ push, pull_request ]
env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3000m"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          bundler-cache: true

      - run: bundle exec fastlane tests

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: "Artifacts"
          path: "artifacts"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/test-results/**/TEST-*.xml'

  release:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    env:
      PLAY_PUBLISH: ${{ secrets.PLAY_PUBLISH }}
      SIGNING_KEYSTORE: ${{ secrets.SIGNING_KEYSTORE }}
      SIGNING_PROPERTIES: ${{ secrets.SIGNING_PROPERTIES }}
      GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          bundler-cache: true

      - run: bundle exec fastlane publish_play
